<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('clientes')->insert([
            // === Clientes Casados (con cónyuge) ===
            [
                'nombre_cliente' => 'Juan',
                'apellido_cliente' => 'Pérez',
                'cuit_cliente' => '20-12301678-9',
                'dni_cliente' => '12301678',
                'fecha_nacimiento_cliente' => '1985-05-10',
                'celular_cliente' => '+54 9 11 5555-1234',
                'email_cliente' => 'juan.perez@example.com',
                'estado_civil_cliente' => 'Casado',
                'id_conyugue_cliente' => 1, // Laura Martínez
                'calle' => 'Av. Corrientes 1234',
                'ciudad' => 'Buenos Aires',
                'provincia' => 'Buenos Aires',
                'profesion' => 'Contador',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_cliente' => 'Carlos',
                'apellido_cliente' => 'Fernández',
                'cuit_cliente' => '20-33445566-7',
                'dni_cliente' => '33445566',
                'fecha_nacimiento_cliente' => '1980-01-15',
                'celular_cliente' => '+54 9 11 5555-9012',
                'email_cliente' => 'carlos.fernandez@example.com',
                'estado_civil_cliente' => 'En Concubinato',
                'id_conyugue_cliente' => 2, // Sofía López
                'calle' => 'San Martín 456',
                'ciudad' => 'Rosario',
                'provincia' => 'Santa Fe',
                'profesion' => 'Ingeniero',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_cliente' => 'Diego',
                'apellido_cliente' => 'Ramírez',
                'cuit_cliente' => '20-55667788-4',
                'dni_cliente' => '55667788',
                'fecha_nacimiento_cliente' => '1990-03-20',
                'celular_cliente' => '+54 9 11 5555-7890',
                'email_cliente' => 'diego.ramirez@example.com',
                'estado_civil_cliente' => 'Casado',
                'id_conyugue_cliente' => 3, // Martín García
                'calle' => 'Belgrano 789',
                'ciudad' => 'Córdoba',
                'provincia' => 'Córdoba',
                'profesion' => 'Abogado',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_cliente' => 'Mariana Mabel',
                'apellido_cliente' => 'López',
                'cuit_cliente' => '20-77778888-5',
                'dni_cliente' => '77778888',
                'fecha_nacimiento_cliente' => '1988-09-22',
                'celular_cliente' => '+54 9 11 5555-4444',
                'email_cliente' => 'mariana.lopez@example.com',
                'estado_civil_cliente' => 'Casada',
                'id_conyugue_cliente' => 4, // Manuel Morales
                'calle' => 'Mitre 123',
                'ciudad' => 'La Plata',
                'provincia' => 'Buenos Aires',
                'profesion' => 'Arquitecta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_cliente' => 'Lucía',
                'apellido_cliente' => 'Gómez',
                'cuit_cliente' => '27-99887786-1',
                'dni_cliente' => '99887786',
                'fecha_nacimiento_cliente' => '1993-06-05',
                'celular_cliente' => '+54 9 11 5555-5555',
                'email_cliente' => 'lucia.gomez@example.com',
                'estado_civil_cliente' => 'Casada',
                'id_conyugue_cliente' => 5, // Yesica Vera
                'calle' => 'Urquiza 456',
                'ciudad' => 'Santa Fe',
                'provincia' => 'Santa Fe',
                'profesion' => 'Doctora',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === Clientes Solteros (sin cónyuge) ===
            [
                'nombre_cliente' => 'Andrés',
                'apellido_cliente' => 'Moreno',
                'cuit_cliente' => '20-11223349-5',
                'dni_cliente' => '11223349',
                'fecha_nacimiento_cliente' => '1995-12-12',
                'celular_cliente' => '+54 9 11 5555-6666',
                'email_cliente' => 'andres.moreno@example.com',
                'estado_civil_cliente' => 'Soltero',
                'id_conyugue_cliente' => null,
                'calle' => 'Sarmiento 222',
                'ciudad' => 'Mendoza',
                'provincia' => 'Mendoza',
                'profesion' => 'Analista',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_cliente' => 'Florencia',
                'apellido_cliente' => 'Vega',
                'cuit_cliente' => '27-22004455-6',
                'dni_cliente' => '22004455',
                'fecha_nacimiento_cliente' => '1998-08-01',
                'celular_cliente' => '+54 9 11 5555-7777',
                'email_cliente' => 'florencia.vega@example.com',
                'estado_civil_cliente' => 'Soltera',
                'id_conyugue_cliente' => null,
                'calle' => 'Italia 999',
                'ciudad' => 'Tucumán',
                'provincia' => 'Tucumán',
                'profesion' => 'Diseñadora',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_cliente' => 'Lucas',
                'apellido_cliente' => 'Molina',
                'cuit_cliente' => '20-44555377-8',
                'dni_cliente' => '44555377',
                'fecha_nacimiento_cliente' => '1989-02-14',
                'celular_cliente' => '+54 9 11 5555-8888',
                'email_cliente' => 'lucas.molina@example.com',
                'estado_civil_cliente' => 'Soltero',
                'id_conyugue_cliente' => null,
                'calle' => 'Rivadavia 850',
                'ciudad' => 'Salta',
                'provincia' => 'Salta',
                'profesion' => 'Programador',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_cliente' => 'Natalia',
                'apellido_cliente' => 'Suárez',
                'cuit_cliente' => '27-55662788-9',
                'dni_cliente' => '55662788',
                'fecha_nacimiento_cliente' => '1991-03-09',
                'celular_cliente' => '+54 9 11 5555-9999',
                'email_cliente' => 'natalia.suarez@example.com',
                'estado_civil_cliente' => 'Soltera',
                'id_conyugue_cliente' => null,
                'calle' => 'Belgrano 432',
                'ciudad' => 'Posadas',
                'provincia' => 'Misiones',
                'profesion' => 'Maestra',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_cliente' => 'Tomás',
                'apellido_cliente' => 'Herrera',
                'cuit_cliente' => '20-66770099-0',
                'dni_cliente' => '66770099',
                'fecha_nacimiento_cliente' => '1987-11-03',
                'celular_cliente' => '+54 9 11 5555-0000',
                'email_cliente' => 'tomas.herrera@example.com',
                'estado_civil_cliente' => 'Soltero',
                'id_conyugue_cliente' => null,
                'calle' => 'Colón 765',
                'ciudad' => 'San Juan',
                'provincia' => 'San Juan',
                'profesion' => 'Electricista',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
